create table if not exists public.datasets (
  id bigint generated by default as identity primary key,
  filename text not null,
  storage_key text not null,
  status text not null default 'uploaded',
  created_by text not null,
  created_at timestamptz not null default now()
);

create index if not exists datasets_created_by_idx on public.datasets (created_by);
create index if not exists datasets_created_at_idx on public.datasets (created_at desc);

alter table public.datasets enable row level security;

create policy "datasets readable by owner"
on public.datasets
for select
using (created_by = auth.jwt() ->> 'email');

create policy "datasets insertable by owner"
on public.datasets
for insert
with check (created_by = auth.jwt() ->> 'email');

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null default '',
  owner text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.dataset_versions (
  id bigint generated by default as identity primary key,
  dataset_id bigint references public.datasets(id) on delete set null,
  version text not null unique,
  sha256 text not null,
  row_count integer not null,
  field_count integer not null,
  metadata_json jsonb not null default '{}'::jsonb,
  created_by text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.model_versions (
  id bigint generated by default as identity primary key,
  name text not null,
  version text not null unique,
  model_type text not null,
  feature_schema jsonb not null default '{}'::jsonb,
  settings_json jsonb not null default '{}'::jsonb,
  status text not null default 'active',
  created_by text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.scenarios (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  name text not null,
  inputs jsonb not null,
  validation jsonb not null default '{}'::jsonb,
  dataset_version text not null,
  model_version text not null,
  created_by text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.predictions (
  id bigint generated by default as identity primary key,
  scenario_id bigint not null references public.scenarios(id) on delete cascade,
  output jsonb not null,
  evidence jsonb not null default '[]'::jsonb,
  data_support_score double precision,
  created_at timestamptz not null default now()
);

create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  scenario_id bigint not null references public.scenarios(id) on delete cascade,
  prediction_id bigint references public.predictions(id) on delete set null,
  content jsonb not null,
  sha256 text not null,
  created_by text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.mcp_logs (
  id bigint generated by default as identity primary key,
  project_id bigint references public.projects(id) on delete cascade,
  scenario_id bigint references public.scenarios(id) on delete set null,
  run_id text not null,
  tool_name text not null,
  arguments jsonb not null default '{}'::jsonb,
  output_summary jsonb not null default '{}'::jsonb,
  status text not null,
  latency_ms double precision,
  created_by text not null,
  created_at timestamptz not null default now()
);

create index if not exists projects_owner_idx on public.projects (owner, created_at desc);
create index if not exists scenarios_project_idx on public.scenarios (project_id, created_at desc);
create index if not exists predictions_scenario_idx on public.predictions (scenario_id, created_at desc);
create index if not exists reports_scenario_idx on public.reports (scenario_id, created_at desc);
create index if not exists mcp_logs_project_idx on public.mcp_logs (project_id, created_at desc);
create index if not exists mcp_logs_run_idx on public.mcp_logs (run_id);

alter table public.projects enable row level security;
alter table public.dataset_versions enable row level security;
alter table public.model_versions enable row level security;
alter table public.scenarios enable row level security;
alter table public.predictions enable row level security;
alter table public.reports enable row level security;
alter table public.mcp_logs enable row level security;

create policy "projects owned access" on public.projects
for all using (owner = auth.jwt() ->> 'email')
with check (owner = auth.jwt() ->> 'email');

create policy "dataset versions readable" on public.dataset_versions
for select using (auth.uid() is not null);

create policy "model versions readable" on public.model_versions
for select using (auth.uid() is not null);

create policy "scenarios owned access" on public.scenarios
for all using (created_by = auth.jwt() ->> 'email')
with check (created_by = auth.jwt() ->> 'email');

create policy "predictions owned access" on public.predictions
for select using (
  exists (
    select 1 from public.scenarios s
    where s.id = predictions.scenario_id
      and s.created_by = auth.jwt() ->> 'email'
  )
);

create policy "reports owned access" on public.reports
for all using (created_by = auth.jwt() ->> 'email')
with check (created_by = auth.jwt() ->> 'email');

create policy "mcp logs owned access" on public.mcp_logs
for all using (created_by = auth.jwt() ->> 'email')
with check (created_by = auth.jwt() ->> 'email');
